/**
 * Squarespace order payload shapes aren't formally documented; these are
 * inferred from actual API responses and kept loose (unknown extra fields
 * allowed) rather than fully strict. Confirmed against live data in Aug 2026:
 * course line items now come through as both SERVICE and PAYWALL_PRODUCT, and
 * PAYWALL_PRODUCT items carry null lineItem customizations/variantOptions —
 * checkout answers for those live in the order-level formSubmission instead.
 */

export interface SquarespaceFormSubmissionField {
  label: string;
  value: string;
}

export interface SquarespaceVariantOption {
  optionName: string;
  value: string;
}

export interface SquarespaceLineItem {
  id: string;
  lineItemType: string;
  productId: string;
  productName: string;
  quantity: number;
  unitPricePaid: { currency: string; value: string };
  variantOptions: SquarespaceVariantOption[] | null;
  customizations: SquarespaceFormSubmissionField[] | null;
  [key: string]: unknown;
}

export interface SquarespaceBillingAddress {
  firstName?: string;
  lastName?: string;
  phone?: string;
  [key: string]: unknown;
}

/**
 * Order-level discount, from a redeemed promo code (confirmed against live
 * data, Sep 2026). `promoCode` on a financial-aid award is generated by
 * api/src/lib/discountCode.ts as `FAID-<programCode>-<percentage>-<year>-
 * <suffix>` — that shape is what the scholarships module keys off of to
 * find the order a Zakat-funded award was actually redeemed on.
 */
export interface SquarespaceDiscountLine {
  discountId: string;
  name: string;
  description?: string;
  amount: { currency: string; value: string };
  promoCode: string;
  discountType: string;
  [key: string]: unknown;
}

export interface SquarespaceOrder {
  id: string;
  orderNumber: string;
  createdOn: string;
  modifiedOn: string;
  customerEmail: string;
  billingAddress?: SquarespaceBillingAddress | null;
  formSubmission?: SquarespaceFormSubmissionField[] | null;
  lineItems: SquarespaceLineItem[];
  discountLines?: SquarespaceDiscountLine[];
  discountTotal?: { currency: string; value: string };
  [key: string]: unknown;
}

export interface SquarespacePagination {
  nextPageUrl?: string | null;
  hasNextPage?: boolean;
}

export interface SquarespaceOrdersResponse {
  result?: SquarespaceOrder[];
  pagination?: SquarespacePagination;
}

/**
 * Customer Profiles API shape (inferred from live responses, Aug 2026). This
 * is the Squarespace *account* holder — the person who logs in to reach the
 * paywalled course — as opposed to whatever name/phone was typed into an
 * order's billing form. `hasAccount` is false for guest checkouts that never
 * created a login; in that case there's no account name to trust and callers
 * fall back to the order's billing address.
 */
export interface SquarespaceProfile {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  hasAccount?: boolean;
  address?: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    [key: string]: unknown;
  } | null;
  [key: string]: unknown;
}

export interface SquarespaceProfilesResponse {
  profiles?: SquarespaceProfile[];
  pagination?: SquarespacePagination;
}

/**
 * Products API v2 shape (documented at developers.squarespace.com, Oct
 * 2026). Note there is no `categories` field — store categories aren't
 * exposed by any Squarespace API (checked the public ?format=json feed
 * too), which is why events are flagged with a product *tag* instead. Only
 * PHYSICAL/SERVICE/GIFT_CARD/DIGITAL products exist here; PAYWALL_PRODUCT
 * line items have no Products API counterpart.
 */
export interface SquarespaceProduct {
  id: string;
  type: string;
  name: string;
  tags?: string[] | null;
  isVisible?: boolean;
  createdOn?: string;
  [key: string]: unknown;
}

export interface SquarespaceProductsResponse {
  products?: SquarespaceProduct[];
}
